#pragma once

#include "keyhandling.h"
#define KEY_F1              ((keycode)(  0 << 8 | 59 ))
#define KEY_F2              ((keycode)(  0 << 8 | 60 ))
#define KEY_F3              ((keycode)(  0 << 8 | 61 ))
#define KEY_F4              ((keycode)(  0 << 8 | 62 ))
#define KEY_F5              ((keycode)(  0 << 8 | 63 ))
#define KEY_F6              ((keycode)(  0 << 8 | 64 ))
#define KEY_F7              ((keycode)(  0 << 8 | 65 ))
#define KEY_F8              ((keycode)(  0 << 8 | 66 ))
#define KEY_F9              ((keycode)(  0 << 8 | 67 ))
#define KEY_F10             ((keycode)(  0 << 8 | 68 ))
#define KEY_CTRL_A          ((keycode)(  1 << 8 | 0	 ))
#define KEY_CTRL_B          ((keycode)(  2 << 8 | 0	 ))
#define KEY_CTRL_C          ((keycode)(  3 << 8 | 0	 ))
#define KEY_CTRL_D          ((keycode)(  4 << 8 | 0	 ))
#define KEY_CTRL_E          ((keycode)(  5 << 8 | 0	 ))
#define KEY_CTRL_F          ((keycode)(  6 << 8 | 0	 ))
#define KEY_CTRL_G          ((keycode)(  7 << 8 | 0	 ))
#define KEY_CTRL_H          ((keycode)(  8 << 8 | 0	 ))
#define KEY_CTRL_I          ((keycode)(  9 << 8 | 0	 ))
#define KEY_CTRL_J          ((keycode)( 10 << 8 | 0	 ))
#define KEY_CTRL_K          ((keycode)( 11 << 8 | 0	 ))
#define KEY_CTRL_L          ((keycode)( 12 << 8 | 0	 ))
#define KEY_CTRL_M          ((keycode)( 13 << 8 | 0	 ))
#define KEY_CTRL_N          ((keycode)( 14 << 8 | 0	 ))
#define KEY_CTRL_O          ((keycode)( 15 << 8 | 0	 ))
#define KEY_CTRL_P          ((keycode)( 16 << 8 | 0	 ))
#define KEY_CTRL_Q          ((keycode)( 17 << 8 | 0	 ))
#define KEY_CTRL_R          ((keycode)( 18 << 8 | 0	 ))
#define KEY_CTRL_S          ((keycode)( 19 << 8 | 0	 ))
#define KEY_CTRL_T          ((keycode)( 20 << 8 | 0	 ))
#define KEY_CTRL_U          ((keycode)( 21 << 8 | 0	 ))
#define KEY_CTRL_V          ((keycode)( 22 << 8 | 0	 ))
#define KEY_CTRL_W          ((keycode)( 23 << 8 | 0	 ))
#define KEY_CTRL_X          ((keycode)( 24 << 8 | 0	 ))
#define KEY_CTRL_Y          ((keycode)( 25 << 8 | 0	 ))
#define KEY_CTRL_Z          ((keycode)( 26 << 8 | 0	 ))
#define KEY_ENTER           ((keycode)( 13 << 8 | 0	 ))
#define KEY_ESC             ((keycode)( 27 << 8 | 0	 ))
#define KEY_SPACE           ((keycode)( 32 << 8 | 0	 ))
#define KEY_HASH            ((keycode)( 35 << 8 | 0	 ))
#define KEY_MULTIPLY        ((keycode)( 42 << 8 | 0	 ))
#define KEY_PLUS            ((keycode)( 43 << 8 | 0	 ))
#define KEY_COMMA           ((keycode)( 44 << 8 | 0	 ))
#define KEY_MINUS           ((keycode)( 45 << 8 | 0	 ))
#define KEY_DOT             ((keycode)( 46 << 8 | 0	 ))
#define KEY_DIVIDE          ((keycode)( 47 << 8 | 0	 ))
#define KEY_0               ((keycode)( 48 << 8 | 0	 ))
#define KEY_1               ((keycode)( 49 << 8 | 0	 ))
#define KEY_2               ((keycode)( 50 << 8 | 0	 ))
#define KEY_3               ((keycode)( 51 << 8 | 0	 ))
#define KEY_4               ((keycode)( 52 << 8 | 0	 ))
#define KEY_5               ((keycode)( 53 << 8 | 0	 ))
#define KEY_6               ((keycode)( 54 << 8 | 0	 ))
#define KEY_7               ((keycode)( 55 << 8 | 0	 ))
#define KEY_8               ((keycode)( 56 << 8 | 0	 ))
#define KEY_9               ((keycode)( 57 << 8 | 0	 ))
#define KEY_GREATERTHEN     ((keycode)( 60 << 8 | 0	 ))
#define KEY_A_BIG           ((keycode)( 65 << 8 | 0	 ))
#define KEY_B_BIG           ((keycode)( 66 << 8 | 0	 ))
#define KEY_C_BIG           ((keycode)( 67 << 8 | 0	 ))
#define KEY_D_BIG           ((keycode)( 68 << 8 | 0	 ))
#define KEY_E_BIG           ((keycode)( 69 << 8 | 0	 ))
#define KEY_F_BIG           ((keycode)( 70 << 8 | 0	 ))
#define KEY_G_BIG           ((keycode)( 71 << 8 | 0	 ))
#define KEY_H_BIG           ((keycode)( 72 << 8 | 0	 ))
#define KEY_I_BIG           ((keycode)( 73 << 8 | 0	 ))
#define KEY_J_BIG           ((keycode)( 74 << 8 | 0	 ))
#define KEY_K_BIG           ((keycode)( 75 << 8 | 0	 ))
#define KEY_L_BIG           ((keycode)( 76 << 8 | 0	 ))
#define KEY_M_BIG           ((keycode)( 77 << 8 | 0	 ))
#define KEY_N_BIG           ((keycode)( 78 << 8 | 0	 ))
#define KEY_O_BIG           ((keycode)( 79 << 8 | 0	 ))
#define KEY_P_BIG           ((keycode)( 80 << 8 | 0	 ))
#define KEY_Q_BIG           ((keycode)( 81 << 8 | 0	 ))
#define KEY_R_BIG           ((keycode)( 82 << 8 | 0	 ))
#define KEY_S_BIG           ((keycode)( 83 << 8 | 0	 ))
#define KEY_T_BIG           ((keycode)( 84 << 8 | 0	 ))
#define KEY_U_BIG           ((keycode)( 85 << 8 | 0	 ))
#define KEY_V_BIG           ((keycode)( 86 << 8 | 0	 ))
#define KEY_W_BIG           ((keycode)( 87 << 8 | 0	 ))
#define KEY_X_BIG           ((keycode)( 88 << 8 | 0	 ))
#define KEY_Y_BIG           ((keycode)( 89 << 8 | 0	 ))
#define KEY_Z_BIG           ((keycode)( 90 << 8 | 0	 ))
#define KEY_A_LOW           ((keycode)( 97 << 8 | 0	 ))
#define KEY_B_LOW           ((keycode)( 98 << 8 | 0	 ))
#define KEY_C_LOW           ((keycode)( 99 << 8 | 0	 ))
#define KEY_D_LOW           ((keycode)(100 << 8 | 0	 ))
#define KEY_E_LOW           ((keycode)(101 << 8 | 0	 ))
#define KEY_F_LOW           ((keycode)(102 << 8 | 0	 ))
#define KEY_G_LOW           ((keycode)(103 << 8 | 0	 ))
#define KEY_H_LOW           ((keycode)(104 << 8 | 0	 ))
#define KEY_I_LOW           ((keycode)(105 << 8 | 0	 ))
#define KEY_J_LOW           ((keycode)(106 << 8 | 0	 ))
#define KEY_K_LOW           ((keycode)(107 << 8 | 0	 ))
#define KEY_L_LOW           ((keycode)(108 << 8 | 0	 ))
#define KEY_M_LOW           ((keycode)(109 << 8 | 0	 ))
#define KEY_N_LOW           ((keycode)(110 << 8 | 0	 ))
#define KEY_O_LOW           ((keycode)(111 << 8 | 0	 ))
#define KEY_P_LOW           ((keycode)(112 << 8 | 0	 ))
#define KEY_Q_LOW           ((keycode)(113 << 8 | 0	 ))
#define KEY_R_LOW           ((keycode)(114 << 8 | 0	 ))
#define KEY_S_LOW           ((keycode)(115 << 8 | 0	 ))
#define KEY_T_LOW           ((keycode)(116 << 8 | 0	 ))
#define KEY_U_LOW           ((keycode)(117 << 8 | 0	 ))
#define KEY_V_LOW           ((keycode)(118 << 8 | 0	 ))
#define KEY_W_LOW           ((keycode)(119 << 8 | 0	 ))
#define KEY_X_LOW           ((keycode)(120 << 8 | 0	 ))
#define KEY_Y_LOW           ((keycode)(121 << 8 | 0	 ))
#define KEY_Z_LOW           ((keycode)(122 << 8 | 0	 ))
#define KEY_UE_LOW          ((keycode)(129 << 8 | 0	 ))
#define KEY_AE_LOW          ((keycode)(132 << 8 | 0	 ))
#define KEY_AE_BIG          ((keycode)(142 << 8 | 0	 ))
#define KEY_OE_LOW          ((keycode)(148 << 8 | 0	 ))
#define KEY_OE_BIG          ((keycode)(153 << 8 | 0	 ))
#define KEY_UE_BIG          ((keycode)(154 << 8 | 0	 ))
#define KEY_POS1            ((keycode)(224 << 8 | 71 ))
#define KEY_UPARROW         ((keycode)(224 << 8 | 72 ))
#define KEY_PAGEUP          ((keycode)(224 << 8 | 73 ))
#define KEY_LEFTARROW       ((keycode)(224 << 8 | 75 ))
#define KEY_RIGHTARROW      ((keycode)(224 << 8 | 77 ))
#define KEY_END             ((keycode)(224 << 8 | 79 ))
#define KEY_DOWNARROW       ((keycode)(224 << 8 | 80 ))
#define KEY_PAGEDOWN        ((keycode)(224 << 8 | 81 ))
#define KEY_INSERT          ((keycode)(224 << 8 | 82 ))
#define KEY_DELETE          ((keycode)(224 << 8 | 83 ))
#define KEY_F11             ((keycode)(224 << 8 | 133))
#define KEY_F12             ((keycode)(224 << 8 | 134))
#define KEY_QUESTIONMARK    ((keycode)(225 << 8 | 0	 ))



#define KEY_BACKSPACE         KEY_CTRL_H
#define KEY_TAB               KEY_CTRL_I